// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9-SzPqfB1uX8Lt109NJYMuLp2Lo0TvB0',
    appId: '1:281968604634:web:1ab1d914b67a60fe99fce3',
    messagingSenderId: '281968604634',
    projectId: 'alimtairfianlproject',
    authDomain: 'alimtairfianlproject.firebaseapp.com',
    storageBucket: 'alimtairfianlproject.firebasestorage.app',
    measurementId: 'G-W3LTCNDRWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGR6jzK7pNSLMw8tMKfAmMAGuB2IHdFv8',
    appId: '1:281968604634:android:03413b61bb06edec99fce3',
    messagingSenderId: '281968604634',
    projectId: 'alimtairfianlproject',
    storageBucket: 'alimtairfianlproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4nzMuq3mkudG0GKN-aAQr-TSJ5ZDncrg',
    appId: '1:281968604634:ios:62e1cfba5cd1cecf99fce3',
    messagingSenderId: '281968604634',
    projectId: 'alimtairfianlproject',
    storageBucket: 'alimtairfianlproject.firebasestorage.app',
    iosBundleId: 'com.example.mobFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4nzMuq3mkudG0GKN-aAQr-TSJ5ZDncrg',
    appId: '1:281968604634:ios:62e1cfba5cd1cecf99fce3',
    messagingSenderId: '281968604634',
    projectId: 'alimtairfianlproject',
    storageBucket: 'alimtairfianlproject.firebasestorage.app',
    iosBundleId: 'com.example.mobFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9-SzPqfB1uX8Lt109NJYMuLp2Lo0TvB0',
    appId: '1:281968604634:web:7a5a40f19c43869c99fce3',
    messagingSenderId: '281968604634',
    projectId: 'alimtairfianlproject',
    authDomain: 'alimtairfianlproject.firebaseapp.com',
    storageBucket: 'alimtairfianlproject.firebasestorage.app',
    measurementId: 'G-D2XE55Z86Y',
  );
}
